### ISSUE TITLE
MangaDex not updating some series

### ISSUE THREAD

**Issue by rjbs91** [DakuTree/manga-tracker#329]
## Bug report

**What is the bug?**

There seems to be a problem with MangaDex updating. For me it happens with Gintama, but there may be others also. A new chapter was posted yesterday but the tracker doesn't seem to detect it. It happened before and it took almost a day until the tracker found the new chapter.

**Please provide steps to reproduce:**

Add Gintama to the tracking list and compare the latest chapter in Mangadex with the latest chapter indicated by Manga Tracker.

**Where did the bug happen? (If applicable)**

Manga Tracker (So far only with Gintama in MangaDex, but others may also be affected)

**Comment by DakuTree** [comment]
I'm assuming this happened due to too many updates pushing it off the front page before we could check for the hourly update.

Should be possible to just keep checking the next page until the chapter ID is lower than the one we have stored.  
Will try implementing later today when I have some free time.

**Comment by rjbs91** [comment]
The problems seem to still exist. Mangadex series are not being updated and some of them have been updated 3 days after the release of the latest chapter.

**Comment by DakuTree** [comment]
What series is this happening on?

**Comment by rjbs91** [comment]
The series actually update, but only after 2-3 days from what I experienced.

The ones that, so far, I have problems are:
Bungou Stray Dogs, Gintama, Enen no Shouboutai (still not updated)
Kaguya-sama wa Kokurasetai, Berserk (updated 2 days late). 

I'm following others, but they don't have any new chapters and they seem to have been updated correctly at the time.

**Comment by DakuTree** [comment]
Should be fixed now. MangaDex changed their url format for pages which made us enable to check for updates correctly.

**Comment by rjbs91** [comment]
Just a question. Does MangaDex update hourly or is one of the sites that takes longer to update? If it updates hourly then it didn't update the series.

**Comment by DakuTree** [comment]
It updates hourly by checking https://mangadex.org/0/1/ (and subsequent pages until last chapter ID is hit, or until it passes through 5 pages).  All series are also checked every 3~ days or so if there was no update).  

The series you listed above are not on the first page checked & past the last chapter ID hit so they won't be fixed until the 3 day update comes around

**Comment by rjbs91** [comment]
Ok. That's what I needed to know. Thanks :)

**Comment by rjbs91** [comment]
Sorry to bother again with this issue, but the problem still persists.

I found out that there were updates for Kaguya-sama wa Kokurasetai and Gintama on reddit, however the site still didn't update. Right now Gintama is on page 2 (and the chapter was released 14 hours ago).

**Comment by rjbs91** [comment]
Scratch that. It just updated. But I still find strange how long it took...

**Comment by DakuTree** [comment]
I had a quick look and it seems like it is picking up the chapter properly so I'm not too sure what went wrong.  

My only guess is if MangaDex has something like scheduled (or private) releases, that they won't show on the top of the release list when they are actually made public, instead they'd appear later on in the list according to when they were uploaded. This wouldn't be checked as it's past the last checked chapter ID.  
FoolSlide sites have a similar issue which you can see with daily series like [Mousou Telepathy](http://helveticascans.com/r/series/mousou-telepathy/). Although the group releases new chapters daily, if you look at the above link there is groups of recent chapters that all show the same release date (same also goes to the overall latest release list).

I've done a temp fix which forces the updater to always check the first 3 pages of updates, which should hopefully fix any possible issues that might pop up with this, but honestly it's kind of a hack until MangaDex gets around to implementing an API of sorts.
